version: "3"

services:
  remote-wake-sleep-on-lan-armv7:
    image: koko004/remote-wake-sleep-on-lan-armv7
    container_name: wol
    restart: always
    network_mode: host
    volumes:
      - ./config.php:/var/www/html/config.php
    environment:
      - PASSPHRASE=adminpassword
      - APACHE2_PORT=8080
      - RWSOLS_COMPUTER_NAME=COMPUTER1,COMPUTER2
      - RWSOLS_COMPUTER_MAC="xx:xx:xx:xx:xx:xx","xx:xx:xx:xx:xx:xx"
      - RWSOLS_COMPUTER_IP="xxx.xxx.xxx.xxx","xxx.xxx.xxx.xxx"
